// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4SvAfYX4jpDH1_axJhP1QKTh-TmpRc3c',
    appId: '1:761428304899:web:43b7a46206e9ceb6e05a36',
    messagingSenderId: '761428304899',
    projectId: 'flutterchatapp-18e74',
    authDomain: 'flutterchatapp-18e74.firebaseapp.com',
    storageBucket: 'flutterchatapp-18e74.appspot.com',
    measurementId: 'G-VPLJ20VSQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_HOqjGskG8o9iVfC_XejzCzFxq4qgqL0',
    appId: '1:761428304899:android:61e198fa4f3787cee05a36',
    messagingSenderId: '761428304899',
    projectId: 'flutterchatapp-18e74',
    storageBucket: 'flutterchatapp-18e74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFiw48OPq64GqysQSfjwmhmZutjv-qv4A',
    appId: '1:761428304899:ios:d23ecd915667d6d6e05a36',
    messagingSenderId: '761428304899',
    projectId: 'flutterchatapp-18e74',
    storageBucket: 'flutterchatapp-18e74.appspot.com',
    iosBundleId: 'com.krittamet.flutterchatapp',
  );
}
